data_path: data
eval_args:
  split:
    RS: [0.8, 0.1, 0.1]
  order: RO
  group_by: user
  mode: full

train_batch_size: 4096
eval_batch_size: 4096
valid_metric: NDCG@10
metrics: ["Recall", "NDCG", "Precision", "MAP"]
topk: [1, 2, 3, 4, 5, 10, 20, 30, 50]
epochs: 1000
stopping_step: 10
stoping_step: 20
