embedding_size: 64
n_layers: 3
reg_weight: 1e-4
smt_latent_dim: 64

ssl_temp: 0.1
ssl_reg: 1e-7
hyper_layers: 1

alpha: 1

potential_reg: 8e-8
semantic_reg: 8e-8
num_clusters: 10

m_step: 1
warm_up_step: 20

user_feature_path: features/roberta_user.npy
item_feature_path: features/roberta_item.npy