data_path: ./

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
  inter: [user_id, item_id, rating]
  user : [user_id, post_num, follower, following, timestamp]

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"
val_interval:
  rating: "[0,inf)"